---
repos:
  - repo: "https://github.com/ambv/black"
    rev: "22.12.0"
    hooks:
    - id: "black"
      language_version: "python3.9"
  - repo: "https://github.com/pycqa/flake8"
    rev: "6.0.0"
    hooks:
    - id: "flake8"
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: 'v0.991'
    hooks:
    - id: "mypy"
      additional_dependencies: ["types-cryptography", "types-requests", "types-PyYAML"]
      name: "mypy (client/certgrinder)"
      args: ["--strict"]
  - repo: "https://github.com/pre-commit/mirrors-isort"
    rev: "v5.10.1"
    hooks:
    - id: "isort"
  - repo: "https://github.com/pycqa/pydocstyle"
    rev: "6.1.1"
    hooks:
    - id: "pydocstyle"
