---
name: "Run Tox"

on:  # yamllint disable-line rule:truthy
  push:

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python: ["3.10", "3.11"]
    steps:
      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python }}"

      - name: "Check out main repo"
        uses: "actions/checkout@v2"
        with:
          path: "src"

      - name: "Install remaining python dependencies"
        run: "python -m pip install ./src/"

      - name: "Run Tox"
        run: "tox -e py"
        working-directory: "./src"

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v3"
        with:
          fail_ci_if_error: true
          files: "./src/coverage.xml"
...
